#!/bin/env bash

[ ! -v NTSH_DIR ] && source "utils.sh" || source "$NTSH_DIR/utils.sh"

handle_help "$1" "query notes for tags, keywords, titles"

tags() {
  tags="$(echo "$1" | sed -E "s/\|/\|- /g")"

  entries="$(find . \( -path "./.git" -o -path "./.obsidian" -o -path "./archive" \) -prune -o -type f -name "*.md" -print0 | xargs -0 grep -Eli "\- $tags")"
  echo "$entries"
}

keywords() {
  if [[ -x "$(command -v rg)" ]]; then
    rg -F "$1"
    return 0
  fi

  kw="$1"

  entries="$(find . \( -path "./.git" -o -path "./.obsidian" -o -path "./archive" \) -prune -o -type f -name "*.md" -print0 | xargs -0 grep -Eli "$kw")"
  echo "$entries"
}

title() {
  entries="$(find . \( -path "./.git" -o -path "./.obsidian" -o -path "./archive" \) -prune -false -o -type f -name "*$1*.md")"
  echo "$entries"
}

case "$1" in
  tag|tags|t)
    tags "$2"
    exit 0
    ;;
  keyword|keywords|kw)
    keywords "$2"
    exit 0
    ;;
  title)
    title "$2"
    exit 0
    ;;
  *)
    echo "unknown command: $1"
    exit 1
    ;;
esac
