#!/bin/env bash

if [[ -z "$1" ]]; then
  echo "please provide note name to remove"
  exit 1
fi

escaped_name=$(printf '%s\n' "$1" | sed 's/[][\\.^$*]/\\&/g')

path="$(find -type f -name "$1.md")"

if [[ -z "$path" ]]; then
  echo "note does not exist"
  exit 1
fi

rm "$path"

ref_files=$(find . \( -path "./.git" -o -path "./.obsidian" \) -prune -o -type f -print0 | xargs -0 grep -Eli "$1")

for file in $ref_files; do
  echo "culling $file"
  # sed -i -E "s/\[\[${escaped_name}\]\]/\[\[\.\/redacted.md\|${1}\]\]/g" "$file"
  sed -i -E "s/\[\[${escaped_name}(\|[^]]*)?\]\]/\[\[redacted\|$1\]\]/g" "$file"
  sed -i -E "s/\(*${escaped_name}.md\)/\(.\/redacted.md\)/g" "$file"
done
